### ISSUE TITLE
How can i make filter using querystring

### ISSUE THREAD

**Issue by kmahera** [appbaseio-apps/reactivesearch-starter-app#1]
I trying to run this project in vue i want to run page with default filter which are passed in Query string parament like "http://localhost:8001/?searchtext="product1"

**Comment by siddharthlatest** [comment]
@kmahera All components now have a new prop `URLParams` which when set to `true` uses a URL query string parameter to both read and write the current selected state.

We will be adding this to the docs shortly, but if you are using `v0.5.15` or a later version of reactivesearch, this is available.

**Comment by kmahera** [comment]
can you give me on example MultiList. how to pass category value in parameter ?

**Comment by siddharthlatest** [comment]
@kmahera there is a prop `URLParams` which should be set as `true`. By default, it is false.

Example use:

```
<MultiList
  componentId="exampleML"
  appbaseField="multilist_data"
  title="MultiList with URL Params"
  URLParams={true}
/>
```
