### ISSUE TITLE
trying on windows

### ISSUE THREAD

**Issue by gemini1988** [appbaseio-apps/reactivesearch-starter-app#3]
getting this error

`ERROR in ./~/JSONStream/index.js
Module parse failed: F:\P\reactivesearch-starter-app\node_modules\JSONStream\index.js Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
| #! /usr/bin/env node
|
| 'use strict'
 @ ./~/appbase-js/dist/streaming_request.js 4:17-38
 @ ./~/appbase-js/dist/appbase.js
 @ ./~/@appbaseio/reactivebase/lib/middleware/ReactiveBase.js
 @ ./~/@appbaseio/reactivebase/lib/app.js
 @ ./~/@appbaseio/reactivemaps/lib/app.js
 @ ./~/@appbaseio/reactivesearch/lib/app.js
 @ ./app/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./index.js`

**Comment by metagrover** [comment]
@gemini1988 Do you have shebang-loader present in your webpack config?

Refer this-
https://github.com/appbaseio-apps/reactivesearch-starter-app/blob/master/webpack.config.js#L18-L21

**Comment by gemini1988** [comment]
yeah its thr...  Have cloned the repo

**Comment by gemini1988** [comment]
@metagrover  removing this line 
`#! /usr/bin/env node` from  node_modules\sha.js\bin.js makes it work

**Comment by metagrover** [comment]
If you have the package `shebang-loader` installed and necessary webpack configuration in place, you wouldn't need to remove the `#! /usr/bin/env node` explicitly.

Make sure you have all the packages installed. I've added support for yarn and upgraded `reactivesearch`. Should work now!

**Comment by gemini1988** [comment]
cool 👍
