### ISSUE TITLE
Code update needed.

### ISSUE THREAD

**Issue by zhaodaolimeng** [appbaseio-apps/reactivesearch-starter-app#4]
https://github.com/appbaseio-apps/reactivesearch-starter-app/blob/4c79ca326e326ffec12efd3837402f6c26863ac7/src/App.js#L8
should be changed to the following according to official docs.
```javascript
app="carstore-dataset"
```

**Comment by kwikwag** [comment]
And also the API key is different. Should be 4HWI27QmA:58c731f7-79ab-4f55-a590-7e15c7e36721

**Comment by siddharthlatest** [comment]
Done in #5, closing.
